// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8127z9_BMKDxwGke9kL2B_mVlIyvnxGw',
    appId: '1:364870639702:web:1cbc4e1e3b795e53badbf7',
    messagingSenderId: '364870639702',
    projectId: 'instagramc-3cb6e',
    authDomain: 'instagramc-3cb6e.firebaseapp.com',
    storageBucket: 'instagramc-3cb6e.appspot.com',
    measurementId: 'G-5CQJWY27J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9YVjdquYvLXdy-QfyU-uFx8Vdr8HVO0',
    appId: '1:364870639702:android:be3cef714f07c48bbadbf7',
    messagingSenderId: '364870639702',
    projectId: 'instagramc-3cb6e',
    storageBucket: 'instagramc-3cb6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvtBfCrrWSFVGwuXBx0T6II9yPPYzKD4',
    appId: '1:364870639702:ios:32b7032526252126badbf7',
    messagingSenderId: '364870639702',
    projectId: 'instagramc-3cb6e',
    storageBucket: 'instagramc-3cb6e.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvtBfCrrWSFVGwuXBx0T6II9yPPYzKD4',
    appId: '1:364870639702:ios:dcf5427719197db0badbf7',
    messagingSenderId: '364870639702',
    projectId: 'instagramc-3cb6e',
    storageBucket: 'instagramc-3cb6e.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
